# Generated by Django 3.2.4 on 2021-06-18 09:59

import colorfield.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mission', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=800)),
                ('involvement', models.CharField(max_length=250)),
                ('meeting', models.CharField(max_length=250)),
                ('umbrella', models.CharField(choices=[('ED4ALL', 'Education for All'), ('GI', 'Global Issues'), ('SASCENTRIC', 'SAS-Centric'), ('H4DI', 'Help for the Disabled and Ill'), ('PE', 'Poverty Eradication'), ('NSC', 'New Service Clubs'), ('SP', 'Service Projects')], max_length=20)),
                ('color_primary', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('color_secondary', colorfield.fields.ColorField(default='#1A1A1A', max_length=18)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('series', models.UUIDField(blank=True, null=True)),
                ('location', models.CharField(max_length=50)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='portal.club')),
            ],
            options={
                'ordering': ['startTime'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classOf', models.PositiveIntegerField(blank=True, null=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['firstName'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkInDate', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='portal.club')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='portal.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='portal.userprofile')),
            ],
            options={
                'ordering': ['-checkInDate'],
            },
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='memberClubs', to='portal.UserProfile'),
        ),
        migrations.AddField(
            model_name='club',
            name='officers',
            field=models.ManyToManyField(blank=True, related_name='officerClubs', to='portal.UserProfile'),
        ),
        migrations.AddField(
            model_name='club',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='portal.Tag'),
        ),
    ]
