# Generated by Django 3.2.4 on 2021-07-06 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210704_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_contact_club', to='portal.userprofile'),
        ),
    ]
