# Generated by Django 3.2.4 on 2021-07-08 07:15

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_club_primary_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hours',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(max_length=120000),
        ),
        migrations.AlterField(
            model_name='club',
            name='involvement',
            field=models.CharField(max_length=40000),
        ),
        migrations.AlterField(
            model_name='club',
            name='meeting',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='club',
            name='mission',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=5000, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='umbrella',
            field=models.CharField(choices=[('ED4ALL', 'Education for All'), ('GI', 'Global Issues'), ('SASCENTRIC', 'SAS-Centric'), ('H4DI', 'Help for the Disabled and Ill'), ('PE', 'Poverty Eradication'), ('NSC', 'New Service Clubs'), ('SP', 'Service Projects')], max_length=20000),
        ),
    ]
