# Generated by Django 3.2.4 on 2021-07-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210708_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
