# Generated by Django 3.2.4 on 2021-07-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_club_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=130)),
                ('client_id', models.CharField(max_length=130)),
                ('client_secret', models.CharField(max_length=130)),
            ],
        ),
    ]
