# Generated by Django 3.2.4 on 2021-07-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_gmailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='welcome',
            field=models.CharField(default='default', max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='club',
            name='involvement',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='club',
            name='meeting',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='mission',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='umbrella',
            field=models.CharField(choices=[('ED4ALL', 'Education for All'), ('GI', 'Global Issues'), ('SASCENTRIC', 'SAS-Centric'), ('H4DI', 'Help for the Disabled and Ill'), ('PE', 'Poverty Eradication'), ('NSC', 'New Service Clubs'), ('SP', 'Service Projects')], max_length=200),
        ),
    ]
