# Generated by Django 3.2.4 on 2021-07-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20210714_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GmailToken',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
