# Generated by Django 3.2.4 on 2021-07-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20210714_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='instagram',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
    ]
