# Generated by Django 3.2.4 on 2021-07-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_club_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='involvement',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
