# Generated by Django 3.2.4 on 2022-06-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20210731_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='logo',
        ),
        migrations.AlterField(
            model_name='club',
            name='umbrella',
            field=models.CharField(choices=[('ED4ALL', 'Education for All'), ('GI', 'Global Issues'), ('SASCENTRIC', 'SAS-Centric'), ('H4DI', 'Help for the Disabled and Ill'), ('PE', 'Poverty Eradication'), ('NSC', 'New Service Clubs')], max_length=200),
        ),
    ]
