# Generated by Django 3.2.4 on 2022-08-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20220612_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
