# Generated by Django 3.2.4 on 2022-08-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_meeting',
            field=models.BooleanField(default=False),
        ),
    ]
